---
title: "Chapter 1: Introduction"
author: "Robin Lovelace, Jakub Nowosad, Jannes Muenchow"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{geocompr-solutions1}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

# Chapter 1: Introduction

1) Think about the terms 'GIS', 'GDS' and 'Geocomputation' described above. Which (if any) best describes the work you would like to do using geo* methods and software and why?

- There is no right answer. Your choice may depend on the methods (if it's focussed on spatial relationships and map overlays, GIS may be more appropriate), sector ('data science' is a generic term used in many tech companies) or personal preference.

2) Provide 3 reasons for using a scriptable language such R for geocomputation instead of established GIS programs such as QGIS.

- Reproducibility: a sequence of operations is much easier to save and share when using a scripting language.
- Scalability: scripting languages make it easy to break-up the work and parallelise, making it more scalable.
- Flexibility: the building blocks of the language allows it to interface efficiently with external software, enabling R to perform a wide range of tasks (e.g. animations, online interactive maps).
- Efficiency: the GUI of GIS programs can be slow to use and install.

3) Name two advantages and two disadvantages of using mature packages compared with 'cutting edge' packages for spatial data (for example **sp** vs **sf**).

- `+` Stability (newer packages may be more buggy)
- `+` Number of packages currently supported (although this is changing)
- `-` Slow performance for some operations
- `-` Non standard data representation
- `-` Fewer features
- `-` (Maybe) less future-proof
